CMPUT301F20T15/BookwormAdventuresDeluxe2

app/src/main/res/drawable-v24/status_circle.xml
app/src/main/res/drawable/drop_shadow.xml
app/src/main/res/layout/book_item.xml
app/src/main/res/values/colors.xml

Adding book item layout and updating colors for book status

---

app/src/main/res/drawable-v24/status_circle.xml
app/src/main/res/drawable/drop_shadow.xml
app/src/main/res/layout/book_detail_view.xml
app/src/main/res/values/strings.xml

xml for book detail view

---

.idea/gradle.xml
app/src/main/java/com/example/bookwormadventuresdeluxe2/Book.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/BookListAdapter.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Utilities/Status.java
app/src/main/res/layout/fragment_my_books.xml
app/src/main/res/values/styles.xml

Recycler view for My Books fragment

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/bookwormadventuresdeluxe2/SetLocationActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/ViewLocationActivity.java
app/src/main/res/layout/activity_set_location.xml
app/src/main/res/layout/activity_view_location.xml
app/src/main/res/values/strings.xml

needs map fragment behind as background
https://cmput301.atlassian.net/browse/CMPUT-58

done skeleton

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/MyProfile.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/RequestsFragment.java
app/src/main/res/layout/fragment_requests.xml
app/src/main/res/values/strings.xml

also did other work like
- renamed MyProfile to MyProfileFragment
- removed unused imports in MyProfileFragment

Requests Skeleton

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyProfileFragment.java
app/src/main/res/layout/fragment_my_profile.xml
app/src/main/res/layout/fragment_requests.xml

Renaming MyProfile fixes

---

app/src/main/res/layout/fragment_search.xml

Added a search view in the Search fragment

Search Skeleton

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/example/bookwormadventuresdeluxe2/IsbnScanActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksActivity.java
app/src/main/res/layout/activity_isbn_scan.xml
app/src/main/res/layout/fragment_my_books.xml

Bare bones of the isbn skeleton page

Isbn Scan Skeleton

---

.gitignore
app/build.gradle
app/google-services.json
build.gradle

added '/' to gitignores not working for me

added firebase console

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/MyProfileFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/RequestsFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/SearchFragment.java
app/src/main/res/layout/fragment_my_profile.xml
app/src/main/res/layout/fragment_requests.xml
app/src/main/res/layout/fragment_search.xml
app/src/main/res/values/strings.xml

Add the new app header with the custom icons. Other activities
should do the same when they want to use the new header.
Ticket: https://cmput301.atlassian.net/browse/CMPUT-66

Add app_header to search, requests, and profile

---

.idea/misc.xml
app/src/main/java/com/example/bookwormadventuresdeluxe2/Book.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Notification.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/NotificationFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/NotificationListAdapter.java
app/src/main/res/layout/fragment_notification.xml
app/src/main/res/layout/notification_item.xml
app/src/main/res/values/strings.xml

added functionality to notification icon in MyBooks
added notification class / layout / adapter / fragment
c̶o̶p̶i̶e̶d̶ ̶a̶ ̶l̶o̶t̶ ̶o̶f̶ ̶c̶o̶d̶e̶ ̶f̶r̶o̶m̶ ̶M̶y̶B̶o̶o̶k̶s̶F̶r̶a̶g̶m̶e̶n̶t̶/̶A̶d̶a̶p̶t̶e̶r̶

Notifications skeleton

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/AddOrEditBooksActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/CreateAccountActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/LoginActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksFragment.java
app/src/main/res/layout/activity_edit_books.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Add delete button for books

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/AddOrEditBooksActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Book.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Utilities/EditTextValidator.java
app/src/main/res/layout/activity_edit_books.xml

We can add isbn validator too, if necessary

Validates Book fields before adding/saving

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/AddOrEditBooksActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Book.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/NotificationFragment.java

no requester algorithm or owner.settext implemented

adding owner to book object

---

.gitignore
app/build.gradle
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/LoginActivityTest.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/FirebaseUserGetSet.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyProfileFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Utilities/EditTextValidator.java
app/src/main/res/values/strings.xml

https://cmput301.atlassian.net/browse/CMPUT-75
***********
cannot get R.string.users_collection
in FirebaseUserGetSet without importing application context
tried
Resources.getSystem().getString(android.R.string.users_collection).
and
Resources.getSystem().getString(R.string.users_collection). <---- this one pops up 'Users' but doesnt work??????

done login tests.

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/Book.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/BookListAdapter.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksFragment.java
app/src/main/res/layout/book_detail_view.xml
app/src/main/res/layout/fragment_borrow_detail_view.xml
app/src/main/res/layout/fragment_request_detail_view.xml

Only see books that you own:
Borrower shows in detail view:

Filter by borrower and show borrower in detail view for my books

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyProfileFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/UserProfileObject.java

loading my profile object before opening view so it doesn't blink

myProfile tweak

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/ExitConfirmationDialogFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksActivity.java
app/src/main/res/values/strings.xml

Add safety check on back press

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/CreateAccountActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/FirebaseUserGetSet.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/LoginActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Utilities/EditTextValidator.java

Done create account new errors. Will update createaccount tests tomorrow

Add Create Account Errors

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/bookwormadventuresdeluxe2/SearchFragment.java

- Fixes the text color
- makes all of the search bar clickable

Fix both search bar issues

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/Book.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/BookListAdapter.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/BorrowDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyProfileFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Notification.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/NotificationFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/NotificationListAdapter.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/RequestDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/SetLocationActivity.java

fill out set/view location functions in request / borrow DetailViews
documentation for my classes
enforce location actions during handoff

Activate location buttons

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/BorrowDetailViewFragment.java

changes were accidentally reverted, now re-added
- location buttons in BorrowDetailView
- location logic in BorrowDetailView
- moved header comment
also fixed  bugs with sharing BorrowDetailView >:(
- back button not working in certain situations
- source not getting set when returning from activities

re-added Activate location buttons

---

app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/MyProfileFragmentTest.java

Myprofile test

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksActivity.java
app/src/main/res/values/dimens.xml

Fix navbar crash bug on rapid clicking to change fragment

---

app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/MyBooksFragmentTest.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/SearchFragmentTest.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/TestUtils.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Book.java
app/src/main/res/values/strings.xml

Also adds some utilities for adding books directly through firebase (need to go through the UI to remove them still)

Add filter menu tests

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/RequestDetailViewFragment.java
app/src/main/res/layout/fragment_request_detail_view.xml
app/src/main/res/values/strings.xml

allow viewing profile of selected spinner requester
allow viewing profile of accepted request
enable clicking requester at rPending, bPending, rPending
*cannot see borrower name in myBookS!

view-requester-profile hotfix

---

app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/CreateAccountActivityTest.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/FilterMenuUtils.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/LoginActivityTest.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/MyBooksFilterMenuTests.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/MyBooksFragmentTest.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/MyProfileFragmentTest.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/SearchFragmentTest.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/TestUtils.java

- Always use SHORT_WAIT instead of the default
- Always use NO_WAIT in the case where we already waited and don't need
to wait again

Improve Tests

---

app/build.gradle
app/src/main/java/com/example/bookwormadventuresdeluxe2/BookListAdapter.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/BorrowDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/DetailView.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/RequestDetailViewFragment.java
app/src/main/res/drawable/ic_profile.xml
app/src/main/res/layout/app_header.xml
app/src/main/res/layout/fragment_profile.xml
app/src/main/res/layout/fragment_request_detail_view.xml
app/src/main/res/layout/spinner_item.xml

- Touched up UI for dropdown menu in requests screen
- Added borrowers to MyBooks detail view
- Minor refactoring 
1. Moved clickUsername to parent, DetailView
2. Moved DetailView back to bookworm package since it is a parent class not a utility
- Touched up UI for profile fragment and added dependency for circular imageview

UI Touchups and minor refactoring

---

app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/FilterMenuUtils.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/MyBooksFilterMenuTests.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/MyBooksFragmentTest.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/SearchFragmentTest.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/TestUtils.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/ActiveFragmentTracker.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/BookListAdapter.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/BorrowDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/DetailView.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/NotificationFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/ProfileFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/RequestDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/RequestsFragment.java
app/src/main/res/layout/app_header.xml
app/src/main/res/values/strings.xml

Changed several fragments to use hide and show instead of replace to improve the user experience

Fix fragment transitions

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/BookListAdapter.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/SearchFragment.java
app/src/main/res/layout/fragment_search.xml

Add Search Functionality

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/MyBooksActivity.java

When transitioning to the same fragment, if it is hidden we should
still call the show function.

Fix transitioning to the same fragment

---

app/build.gradle
app/src/main/java/com/example/bookwormadventuresdeluxe2/AddOrEditBooksActivity.java

Some notes:
title, author, description, and book image are all populated automatically.
1. We don't store the images returned by the Google API in firestore, we use the URL directly to simplify things
2. If multiple authors are found, they will be added separated by spaces
3. If a subtitle is found, it will be added to the title in the format "title: Subtitle"

Add extra info to book when scanning ISBN

---

app/src/main/res/layout/activity_login.xml

Add app icon to login activity

---

app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/CreateAccountActivityTest.java
app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/MyProfileFragmentTest.java
app/src/main/res/values/strings.xml

For testing valid username and phone number inputs

Update CreateAccount/Profile Tests

---

app/src/main/res/layout/activity_create_account.xml

Add logo to create account page

---

app/src/androidTest/java/com/example/bookwormadventuresdeluxe2/MyBooksFragmentTest.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Activities/CreateAccountActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Activities/LoginActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Activities/MyBooksActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Controllers/BookListAdapter.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Controllers/NotificationListAdapter.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Fragments/DetailView/BorrowDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Fragments/DetailView/DetailView.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Fragments/DetailView/RequestDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Fragments/FilterMenu.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Fragments/NavigatonBar/MyBooksFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Fragments/NavigatonBar/ProfileFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Fragments/NavigatonBar/RequestsFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Fragments/NavigatonBar/SearchFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Fragments/NotificationFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Models/Book.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Models/Notification.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Models/User.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Utilities/ActiveFragmentTracker.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Utilities/DownloadImageTask.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Utilities/GlobalApplication.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Utilities/NotificationUtility/MyFirebaseMessagingService.java
app/src/main/res/values/strings.xml

=> replace hard coded strings
=> update comments

Verify JavaDoc and Code Cleanup

---

app/src/main/java/com/example/bookwormadventuresdeluxe2/Activities/AddOrEditBooksActivity.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Fragments/DetailView/BorrowDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Fragments/DetailView/MyBooksDetailViewFragment.java
app/src/main/java/com/example/bookwormadventuresdeluxe2/Fragments/DetailView/RequestDetailViewFragment.java
app/src/main/res/layout/activity_view_location.xml
app/src/main/res/values/strings.xml

*Add cancel button for borrower side
(if requester.size after delete == 0, set to Available)
(if requesters.size > 0 after delete, keep Requested)
*MyBooksDetailViewFragment also updates when book changes
Tried to make snapshot listener in superclass for all detailView but failed.
** MY LAST APP CHANGE COMMIT ** going to searchFragmentTest now

Cancel request & hide delete button
